on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: Linux
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.28
        with:
          application: 'MYAPP'
          applicationProcess: 'DEPLOY-MYAPP'
          environment: 'DEV'
          properties: '{"prop1":"${{ vars.PROP1 }}", "prop2":"${{ vars.PROP2 }}"}'
          snapshot: ''
          versions: 'QA-JCL'
          hostname: '${{ secrets.UCD_HOST }}'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'

