on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - 'main'
jobs:
  hello_world_job:
    runs-on: self-ubuntu
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.22
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          properties: '{"prop1":"${{ vars.PROP1 }}", "prop2":"${{ vars.PROP2 }}"}'
          snapshot: ''
          versions: ''
          hostname: '${{ secrets.UCD_HOST }}'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'

